This was making my life difficult since last few days. Although I have't had a chance to look on this issue, but now here you go.
The subject missing error was coming on the console again and again although it was sending emails.

In case of any error like missing subject it was sending email again and again. 
I see the orderComplete notification four times on my machine.

Here is the sample log message of one of the service sendShipmentCompleteNotification which was failing:

Exception: org.ofbiz.service.ServiceValidationException
Message: Unknown parameter found: [sendShipmentCompleteNotification.subject]
---- stack trace ---------------------------------------------------------------
org.ofbiz.service.ServiceValidationException: Unknown parameter found: [sendShipmentCompleteNotification.subject]
org.ofbiz.service.ModelService.validate(ModelService.java:638)
org.ofbiz.service.ModelService.validate(ModelService.java:552)
org.ofbiz.service.ServiceDispatcher.runSync(ServiceDispatcher.java:482)
org.ofbiz.service.ServiceDispatcher.runSync(ServiceDispatcher.java:221)
org.ofbiz.service.GenericDispatcher.runSync(GenericDispatcher.java:159)
org.ofbiz.service.job.GenericServiceJob.exec(GenericServiceJob.java:70)
org.ofbiz.service.job.JobInvoker.run(JobInvoker.java:242)
java.lang.Thread.run(Thread.java:619)

git-svn-id: https://svn.apache.org/repos/asf/ofbiz/trunk@799889 13f79535-47bb-0310-9956-ffa450edef68