A patch Ranjit Kumar Singh from  "Error in CSV download" https://issues.apache.org/jira/browse/OFBIZ-4873
If sorting is enabled for at least one field in the list type form-widget, we get an error, here is the  details:

Error executing macro: renderFieldTitle
required parameter: id is not specified.
The problematic instruction:
----------
==> macro renderFieldTitle [on line 53, column 1 in component://widget/templates/csvFormMacroLibrary.ftl]
in user-directive renderFieldTitle [on line 116, column 57 in component://widget/templates/csvFormMacroLibrary.ftl]
in user-directive renderSortField [on line 1, column 1 in Fri May 11 12:33:29 IST 2012]
----------

Java backtrace for programmers:
----------
freemarker.template.TemplateException: Error executing macro: renderFieldTitle
required parameter: id is not specified.
at freemarker.core.Macro$Context.sanityCheck(Macro.java:211)

Adding a default empty string to the id parameter fixes the issue

git-svn-id: https://svn.apache.org/repos/asf/ofbiz/trunk@1338570 13f79535-47bb-0310-9956-ffa450edef68